// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOvQ-mRs2mCVWfrSM8FwBJ0HIUUjS_IN8',
    appId: '1:182741033146:web:e71b634e4ab8469bde6283',
    messagingSenderId: '182741033146',
    projectId: 'my-flutter-app-b0280',
    authDomain: 'my-flutter-app-b0280.firebaseapp.com',
    storageBucket: 'my-flutter-app-b0280.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqUOSKI6v3cqcEDURQuPCvAmIok_IkBKY',
    appId: '1:182741033146:android:2c043323f1528755de6283',
    messagingSenderId: '182741033146',
    projectId: 'my-flutter-app-b0280',
    storageBucket: 'my-flutter-app-b0280.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3nqptK8rxkmefwzfQtoNSoj2w5fDLKx4',
    appId: '1:182741033146:ios:d54291379743ca68de6283',
    messagingSenderId: '182741033146',
    projectId: 'my-flutter-app-b0280',
    storageBucket: 'my-flutter-app-b0280.appspot.com',
    iosBundleId: 'com.example.myFlutterApp',
  );
}
